### ISSUE TITLE
UndefVarError: http_get not defined

### ISSUE THREAD

**Issue by daschw** [samoconnor/InfoZIP.jl#11]
I tried to run the examples provided in the [open_zip section of the README](https://github.com/samoconnor/InfoZIP.jl#open_zip), but I get `UndefVarError: http_get not defined`. Do I need an additional package providing this?

```julia
julia> Pkg.status("InfoZIP")
 - InfoZIP                       0.1.6

julia> versioninfo()
Julia Version 0.6.4
Commit 9d11f62bcb* (2018-07-09 19:09 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i5-7300U CPU @ 2.60GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Haswell MAX_THREADS=16)
  LAPACK: libopenblas64_
  LIBM: libopenlibm
  LLVM: libLLVM-3.9.1 (ORCJIT, broadwell)
```

**Comment by samoconnor** [comment]
Hi @daschw,

I'm afraid the `http_get` call in the example is only intended to be illustrative and is not a real function :(

You'll want to check out https://github.com/JuliaWeb/HTTP.jl

Try something like:
```julia
using HTTP

r = HTTP.get("http://foo.com/my.zip")
open_zip(r.body)
```

**Comment by daschw** [comment]
OK, thanks a lot!
That was not obvious for me from looking at the README.
